### ISSUE TITLE
Untextured Block

### ISSUE THREAD

**Issue by Rekch2** [InfamousMusicify/FamousBros-Faithful-Venom#1]
Heyy :) Crimson trapdoor on Pack Release Candidate 3 doesnt have texture. Keep up the good work, I love this texture pack

**Comment by InfamousMusicify** [comment]
Currently Building a version to deal with this and a few other visual errors.
Thank you for reporting the issue <3
Should have a version with a fix within a day or so.

**Comment by InfamousMusicify** [comment]
Release Candidate 7 addresses the issue and a few similar issues.
Thanks again for the issue report and feedback!
Glad you like the pack!
