### ISSUE TITLE
Untextured Oxeye Daisy

### ISSUE THREAD

**Issue by Rekch2** [InfamousMusicify/FamousBros-Faithful-Venom#2]
Hey, it's me again XD. First of all, thank you for fixing the crimson trapdoor. But this time its Oxeye Daisy is having the problem.

**Comment by InfamousMusicify** [comment]
🤦‍♂️ I swear i spent 2 hours fixing these errors last night haha 😂
Alrighty im gonna take a look at the files today and work out the rotational block kinks.

**Comment by InfamousMusicify** [comment]
So, it was my bad, I Zipped the wrong Version as Rc-7.  Facepalm.
Rc-8 Will have updated rotational textures.
